//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.8
//
// <auto-generated>
//
// Generated from file `server.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.example.myapplication;

/** @hidden */
public class _ServerPrxI extends com.zeroc.Ice._ObjectPrxI implements ApplicationArchitecturesDistribuees.ServerPrx
{
    /** @hidden */
    public static final long serialVersionUID = 0L;
}
